In [839]:
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [841]:
df=pd.read_csv(r'C:\Users\Youcode\challenges\avito.csv')

In [843]:
df.head()

,titre,localisation,prix,N_chambre,N_salles_bain,surface,etage,Type,description,equipements,lien_annonce
0,grand studio à louer meublé racine,Casablanca,8 500 DH,1.0,1.0,NaN,1,"Appartements, à louer",Appartement de 70m à louer racine une grande c...,"equipements : Ascenseur,Chauffage,Climatisatio...",https://www.avito.ma/fr/racine/appartements/gr...
1,studio vide à louer palmier,Casablanca,5 000 DH,1.0,1.0,NaN,2,"Appartements, à louer",Joli studio vide quartier palmier au 2 eme eta...,"equipements : Ascenseur,Balcon,Chauffage,Clima...",https://www.avito.ma/fr/palmier/appartements/s...
2,Appartement vide 135m² La Gironde,Casablanca,7 000 DH,3.0,2.0,135.0,3,"Appartements, à louer","Appartement vide à louer, situé à La Gironde ,...","equipements : Ascenseur,Balcon,Concierge,Cuisi...",https://www.avito.ma/fr/la_gironde/appartement...
3,Appartement meublé 60 m² à Tamaris,Tamaris,4 000 DH,2.0,1.0,60.0,4,"Appartements, à louer",Location appartement bien meublé et équipé à J...,"equipements : Ascenseur,Balcon,Climatisation,C...",https://www.avito.ma/fr/tamaris/appartements/A...
4,Maison 80m² Ain Diab,Casablanca,6 500 DH,2.0,2.0,80.0,NaN,"Maisons et Villas, à louer","Location Maison à Ain Diab, proche Bd de la co...","equipements : Balcon,Cuisine Équipée",https://www.avito.ma/fr/a%C3%AFn_diab/maisons_...

In [845]:
print(f'rows:{df.shape[0]} columns:{df.shape[1]}')

rows:682 columns:11

In [847]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   titre          680 non-null    object
 1   localisation   680 non-null    object
 2   prix           629 non-null    object
 3   N_chambre      680 non-null    float64
 4   N_salles_bain  668 non-null    float64
 5   surface        438 non-null    float64
 6   etage          634 non-null    object
 7   Type           680 non-null    object
 8   description    680 non-null    object
 9   equipements    682 non-null    object
 10  lien_annonce   682 non-null    object
dtypes: float64(3), object(8)
memory usage: 58.7+ KB

In [849]:
df.drop_duplicates(inplace=True)

In [851]:
print(f'rows:{df.shape[0]} columns:{df.shape[1]}')

rows:598 columns:11

In [853]:
df['prix']

0      8 500 DH
1      5 000 DH
2      7 000 DH
3      4 000 DH
4      6 500 DH
         ...
676    4 500 DH
677    7 500 DH
678    3 000 DH
679    1 800 DH
681    2 500 DH
Name: prix, Length: 598, dtype: object

In [854]:
df['prix'] = df['prix'].str.replace(r'[\u202f DH]', '', regex=True)
df['prix'] = pd.to_numeric(df['prix'], errors='coerce')

In [857]:
df.head()

,titre,localisation,prix,N_chambre,N_salles_bain,surface,etage,Type,description,equipements,lien_annonce
0,grand studio à louer meublé racine,Casablanca,8500.0,1.0,1.0,NaN,1,"Appartements, à louer",Appartement de 70m à louer racine une grande c...,"equipements : Ascenseur,Chauffage,Climatisatio...",https://www.avito.ma/fr/racine/appartements/gr...
1,studio vide à louer palmier,Casablanca,5000.0,1.0,1.0,NaN,2,"Appartements, à louer",Joli studio vide quartier palmier au 2 eme eta...,"equipements : Ascenseur,Balcon,Chauffage,Clima...",https://www.avito.ma/fr/palmier/appartements/s...
2,Appartement vide 135m² La Gironde,Casablanca,7000.0,3.0,2.0,135.0,3,"Appartements, à louer","Appartement vide à louer, situé à La Gironde ,...","equipements : Ascenseur,Balcon,Concierge,Cuisi...",https://www.avito.ma/fr/la_gironde/appartement...
3,Appartement meublé 60 m² à Tamaris,Tamaris,4000.0,2.0,1.0,60.0,4,"Appartements, à louer",Location appartement bien meublé et équipé à J...,"equipements : Ascenseur,Balcon,Climatisation,C...",https://www.avito.ma/fr/tamaris/appartements/A...
4,Maison 80m² Ain Diab,Casablanca,6500.0,2.0,2.0,80.0,NaN,"Maisons et Villas, à louer","Location Maison à Ain Diab, proche Bd de la co...","equipements : Balcon,Cuisine Équipée",https://www.avito.ma/fr/a%C3%AFn_diab/maisons_...

In [858]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 598 entries, 0 to 681
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   titre          596 non-null    object
 1   localisation   596 non-null    object
 2   prix           553 non-null    float64
 3   N_chambre      596 non-null    float64
 4   N_salles_bain  588 non-null    float64
 5   surface        387 non-null    float64
 6   etage          557 non-null    object
 7   Type           596 non-null    object
 8   description    596 non-null    object
 9   equipements    598 non-null    object
 10  lien_annonce   598 non-null    object
dtypes: float64(4), object(7)
memory usage: 56.1+ KB

In [859]:
df['etage'] = pd.to_numeric(df['etage'], errors='coerce')

In [863]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 598 entries, 0 to 681
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   titre          596 non-null    object
 1   localisation   596 non-null    object
 2   prix           553 non-null    float64
 3   N_chambre      596 non-null    float64
 4   N_salles_bain  588 non-null    float64
 5   surface        387 non-null    float64
 6   etage          504 non-null    float64
 7   Type           596 non-null    object
 8   description    596 non-null    object
 9   equipements    598 non-null    object
 10  lien_annonce   598 non-null    object
dtypes: float64(5), object(6)
memory usage: 56.1+ KB

In [864]:
df['etage']

0      1.0
1      2.0
2      3.0
3      4.0
4      NaN
      ...
676    NaN
677    8.0
678    2.0
679    3.0
681    NaN
Name: etage, Length: 598, dtype: float64

In [865]:
data_nemeric = ['prix','N_chambre','N_salles_bain','surface', 'etage']
for d_n in data_nemeric:
    mean = df[d_n].mean()
    median = df[d_n].median()
    std = df[d_n].std()
    skew=df[d_n].skew()
    print(f"Column: {d_n}")
    print(f"Mean: {mean}, Median: {median}, Std: {std}, Skewness: {skew}")
    print("---")

Column: prix
Mean: 12488.05424954792, Median: 6000.0, Std: 64525.12878817924, Skewness: 14.373727588450558
---
Column: N_chambre
Mean: 2.120805369127517, Median: 2.0, Std: 0.861210808207141, Skewness: 1.127344970456994
---
Column: N_salles_bain
Mean: 2.1547619047619047, Median: 2.0, Std: 6.626943695028773, Skewness: 12.217837369480144
---
Column: surface
Mean: 121.21447028423772, Median: 84.0, Std: 157.34844010520067, Skewness: 6.502712507791407
---
Column: etage
Mean: 2.607142857142857, Median: 2.0, Std: 1.385966504831012, Skewness: 0.9756224968166662
---

# all columns show positive skew which means they are asymmetric so we need to use median imputation

In [870]:
data_nemeric = ['prix','N_chambre','N_salles_bain','surface', 'etage']
df_median_imputation=df.copy()
for d_n in data_nemeric:
    percentage_before = (df_median_imputation[d_n].isna().sum() / len(df_median_imputation[d_n])) * 100
    df_median_imputation[d_n].fillna(df_median_imputation[d_n].median(), inplace = True)
    percentage_after = (df_median_imputation[d_n].isna().sum() / len(df_median_imputation[d_n])) * 100
    print(f'{d_n}:percentage of nan value {percentage_before} and after imputation{percentage_after}')
    print('---------------')

prix:percentage of nan value 7.5250836120401345 and after imputation0.0
---------------
N_chambre:percentage of nan value 0.33444816053511706 and after imputation0.0
---------------
N_salles_bain:percentage of nan value 1.6722408026755853 and after imputation0.0
---------------
surface:percentage of nan value 35.28428093645485 and after imputation0.0
---------------
etage:percentage of nan value 15.719063545150503 and after imputation0.0
---------------

C:\Users\Youcode\AppData\Local\Temp\ipykernel_964\2544672522.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_median_imputation[d_n].fillna(df_median_imputation[d_n].median(), inplace = True)

 print('______________methode II(knn)______________________')
df_knn_imputation=df.copy()
df_knn_imputation = df_knn_imputation.groupby('localisation').filter(lambda x: len(x) > 1)
imputer = KNNImputer(n_neighbors=2)
def knn_impute_group(group):
    group_nemeric=group[['prix','N_chambre','N_salles_bain','surface', 'etage']]
    group_imputed = pd.DataFrame(imputer.fit_transform(group_nemeric), columns=['prix','N_chambre','N_salles_bain','surface', 'etage'] )
    group[['prix', 'N_chambre', 'N_salles_bain', 'surface', 'etage']] = group_imputed
    return group
df_knn_imputation = df_knn_imputation.groupby('localisation').apply(knn_impute_group).reset_index(drop=True)

In [871]:
df_median_imputation

,titre,localisation,prix,N_chambre,N_salles_bain,surface,etage,Type,description,equipements,lien_annonce
0,grand studio à louer meublé racine,Casablanca,8500.0,1.0,1.0,84.0,1.0,"Appartements, à louer",Appartement de 70m à louer racine une grande c...,"equipements : Ascenseur,Chauffage,Climatisatio...",https://www.avito.ma/fr/racine/appartements/gr...
1,studio vide à louer palmier,Casablanca,5000.0,1.0,1.0,84.0,2.0,"Appartements, à louer",Joli studio vide quartier palmier au 2 eme eta...,"equipements : Ascenseur,Balcon,Chauffage,Clima...",https://www.avito.ma/fr/palmier/appartements/s...
2,Appartement vide 135m² La Gironde,Casablanca,7000.0,3.0,2.0,135.0,3.0,"Appartements, à louer","Appartement vide à louer, situé à La Gironde ,...","equipements : Ascenseur,Balcon,Concierge,Cuisi...",https://www.avito.ma/fr/la_gironde/appartement...
3,Appartement meublé 60 m² à Tamaris,Tamaris,4000.0,2.0,1.0,60.0,4.0,"Appartements, à louer",Location appartement bien meublé et équipé à J...,"equipements : Ascenseur,Balcon,Climatisation,C...",https://www.avito.ma/fr/tamaris/appartements/A...
4,Maison 80m² Ain Diab,Casablanca,6500.0,2.0,2.0,80.0,2.0,"Maisons et Villas, à louer","Location Maison à Ain Diab, proche Bd de la co...","equipements : Balcon,Cuisine Équipée",https://www.avito.ma/fr/a%C3%AFn_diab/maisons_...
...,...,...,...,...,...,...,...,...,...,...,...
676,Studio neuf à louer 48 m² à Casablanca,Casablanca,4500.0,1.0,1.0,65.0,2.0,"Appartements, à louer",joli studio neuf en Location à Casablanca maar...,"equipements : Ascenseur,Balcon,Chauffage,Clima...",https://www.avito.ma/fr/maarif/appartements/St...
677,appartement à louer à Tanger,Tanger,7500.0,2.0,2.0,84.0,8.0,"Appartements, à louer",Notre Agence Yellow House immo vous présente u...,"equipements : Ascenseur,Climatisation,Cuisine ...",https://www.avito.ma/fr/malabata/appartements/...
678,شقة مفروشة,El Jadida,3000.0,2.0,2.0,80.0,2.0,"Appartements, à louer",شقة مفروشة للكراء الجوهرة في الطابق الثاني كتك...,"equipements : Ascenseur,Balcon,Chauffage,Clima...",https://www.avito.ma/fr/jawhara/appartements/%...
679,حي مولاي عبد الله قرب مقهى كنوز,Casablanca,1800.0,1.0,1.0,40.0,3.0,"Appartements, à louer",برطما للكراء حي مولاي عبد الله في السطح ضالة كيت,equipements :,https://www.avito.ma/fr/a%C3%AFn_chock/apparte...
681,Appartement à louer à Nasime,Mohammedia,2500.0,2.0,1.0,60.0,2.0,"Appartements, à louer",Appartement à louer à Nasime 2 pièces salons c...,"equipements : Parking,Sécurité",https://www.avito.ma/vi/52489225.htm

# outlier detection and treatment

In [875]:
data_nemeric = ['prix','N_chambre','N_salles_bain','surface', 'etage']
df_outliers=df[[]]
for d_n in data_nemeric:
    Q1 = df_median_imputation[d_n].quantile(0.25)
    Q3 = df_median_imputation[d_n].quantile(0.75)
    IQR = Q3 - Q1
    Limite_inf= Q1 - 1.5 * IQR
    limite_sup= Q3 + 1.5  *IQR
    outliers_for_each_column = df_median_imputation[(df_median_imputation[d_n] < Limite_inf) | (df_median_imputation[d_n] > limite_sup)]
    df_outliers=pd.concat([df_outliers,outliers_for_each_column],ignore_index=True)
df_outliers.drop_duplicates(inplace=True)

In [876]:
df_outliers

,titre,localisation,prix,N_chambre,N_salles_bain,surface,etage,Type,description,equipements,lien_annonce
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,Belle villa fermette à louer à Bsabes Benslimane,Benslimane,45000.0,5.0,4.0,225.0,2.0,"Villas et Riads, à louer",Particulier met en location longue durée (au m...,"equipements : Chauffage,Climatisation,Cuisine ...",https://www.avito.ma/fr/autre_secteur/villas_e...
599,Villa à louer vue sur mer,Temara,25000.0,5.0,4.0,600.0,2.0,"Maisons et Villas, à louer",Villa à louer pied dans l’eau 2 piscine garage...,"equipements : Balcon,Garage,Jardin,Meublé,Park...",https://www.avito.ma/fr/harhoura/maisons_et_vi...
600,Villa Front de Mer avec chauffage centrale,Temara,22000.0,4.0,2.0,84.0,2.0,"Villas et Riads, à louer",A louer jolie villa située dans le centre harh...,equipements :,https://www.avito.ma/vi/55504821.htm
601,Crèche disponible a la location,Rabat,50000.0,5.0,3.0,858.0,2.0,"Villas et Riads, à louer",Crèche disponible a louer ou a vendre dans un ...,"equipements : Balcon,Chauffage,Climatisation,J...",https://www.avito.ma/fr/hay_riad/villas_et_ria...
...,...,...,...,...,...,...,...,...,...,...,...
794,Appartement à louer Bourgogne,Casablanca,7000.0,2.0,2.0,85.0,5.0,"Appartements, à louer",Joli appartement vide ou meublé Bourgogne pas ...,"equipements : Ascenseur,Balcon,Climatisation,C...",https://www.avito.ma/fr/bourgogne/appartements...
795,Appartement 2 Chambres à louer Centre ville Fès,Fès,2800.0,2.0,1.0,84.0,6.0,"Appartements, à louer",Appartement à louer à Fès au centre ville boul...,equipements :,https://www.avito.ma/fr/centre/appartements/Ap...
796,studio meublé a louer à Abdelmoumen,Casablanca,6500.0,1.0,1.0,58.0,5.0,"Appartements, à louer",Serraj immobilier\nÀ louer : Magnifique studio...,"equipements : Ascenseur,Balcon,Cuisine Équipée...",https://www.avito.ma/fr/abdelmoumen/appartemen...
800,appartement meublé,Tanger,4000.0,2.0,1.0,84.0,6.0,"Appartements, à louer",Très bel appartement meuble a louer pour les f...,"equipements : Ascenseur,Balcon,Concierge,Cuisi...",https://www.avito.ma/fr/moujahidine/appartemen...
801,appartement à louer à Tanger,Tanger,7500.0,2.0,2.0,84.0,8.0,"Appartements, à louer",Notre Agence Yellow House immo vous présente u...,"equipements : Ascenseur,Climatisation,Cuisine ...",https://www.avito.ma/fr/malabata/appartements/...

In [877]:
data_to_be_normalized=df_median_imputation[['prix','N_chambre','N_salles_bain','surface', 'etage']]
minmax_scaler= MinMaxScaler()
normalized_data=minmax_scaler.fit_transform(data_to_be_normalized)
normalized_data

array([[0.00732553, 0.        , 0.01      , 0.03506908, 0.        ],
       [0.00425495, 0.        , 0.01      , 0.03506908, 0.14285714],
       [0.00600956, 0.28571429, 0.02      , 0.06216791, 0.28571429],
       ...,
       [0.00250033, 0.14285714, 0.02      , 0.03294368, 0.14285714],
       [0.00144756, 0.        , 0.01      , 0.01168969, 0.28571429],
       [0.00206167, 0.14285714, 0.01      , 0.02231668, 0.14285714]])

In [878]:
type(normalized_data)

numpy.ndarray

In [883]:
normalized_df=pd.DataFrame(normalized_data,columns=data_to_be_normalized.columns)
normalized_df

         prix  N_chambre  N_salles_bain   surface     etage
0    0.007326   0.000000           0.01  0.035069  0.000000
1    0.004255   0.000000           0.01  0.035069  0.142857
2    0.006010   0.285714           0.02  0.062168  0.285714
3    0.003378   0.142857           0.01  0.022317  0.428571
4    0.005571   0.142857           0.02  0.032944  0.142857
..        ...        ...            ...       ...       ...
593  0.003816   0.000000           0.01  0.024973  0.142857
594  0.006448   0.142857           0.02  0.035069  1.000000
595  0.002500   0.142857           0.02  0.032944  0.142857
596  0.001448   0.000000           0.01  0.011690  0.285714
597  0.002062   0.142857           0.01  0.022317  0.142857

[598 rows x 5 columns]

In [884]:
columns=['prix','N_chambre','N_salles_bain','surface', 'etage']
for column in columns:
    df_median_imputation[column]=normalized_df[column]

In [885]:
df_median_imputation.head()

,titre,localisation,prix,N_chambre,N_salles_bain,surface,etage,Type,description,equipements,lien_annonce
0,grand studio à louer meublé racine,Casablanca,0.007326,0.000000,0.01,0.035069,0.000000,"Appartements, à louer",Appartement de 70m à louer racine une grande c...,"equipements : Ascenseur,Chauffage,Climatisatio...",https://www.avito.ma/fr/racine/appartements/gr...
1,studio vide à louer palmier,Casablanca,0.004255,0.000000,0.01,0.035069,0.142857,"Appartements, à louer",Joli studio vide quartier palmier au 2 eme eta...,"equipements : Ascenseur,Balcon,Chauffage,Clima...",https://www.avito.ma/fr/palmier/appartements/s...
2,Appartement vide 135m² La Gironde,Casablanca,0.006010,0.285714,0.02,0.062168,0.285714,"Appartements, à louer","Appartement vide à louer, situé à La Gironde ,...","equipements : Ascenseur,Balcon,Concierge,Cuisi...",https://www.avito.ma/fr/la_gironde/appartement...
3,Appartement meublé 60 m² à Tamaris,Tamaris,0.003378,0.142857,0.01,0.022317,0.428571,"Appartements, à louer",Location appartement bien meublé et équipé à J...,"equipements : Ascenseur,Balcon,Climatisation,C...",https://www.avito.ma/fr/tamaris/appartements/A...
4,Maison 80m² Ain Diab,Casablanca,0.005571,0.142857,0.02,0.032944,0.142857,"Maisons et Villas, à louer","Location Maison à Ain Diab, proche Bd de la co...","equipements : Balcon,Cuisine Équipée",https://www.avito.ma/fr/a%C3%AFn_diab/maisons_...

In [886]:
# after normalization and cleaned the df again
clean_normalized_df= df_median_imputation[df_median_imputation['prix'].notna()]

In [887]:
clean_normalized_df

,titre,localisation,prix,N_chambre,N_salles_bain,surface,etage,Type,description,equipements,lien_annonce
0,grand studio à louer meublé racine,Casablanca,0.007326,0.000000,0.01,0.035069,0.000000,"Appartements, à louer",Appartement de 70m à louer racine une grande c...,"equipements : Ascenseur,Chauffage,Climatisatio...",https://www.avito.ma/fr/racine/appartements/gr...
1,studio vide à louer palmier,Casablanca,0.004255,0.000000,0.01,0.035069,0.142857,"Appartements, à louer",Joli studio vide quartier palmier au 2 eme eta...,"equipements : Ascenseur,Balcon,Chauffage,Clima...",https://www.avito.ma/fr/palmier/appartements/s...
2,Appartement vide 135m² La Gironde,Casablanca,0.006010,0.285714,0.02,0.062168,0.285714,"Appartements, à louer","Appartement vide à louer, situé à La Gironde ,...","equipements : Ascenseur,Balcon,Concierge,Cuisi...",https://www.avito.ma/fr/la_gironde/appartement...
3,Appartement meublé 60 m² à Tamaris,Tamaris,0.003378,0.142857,0.01,0.022317,0.428571,"Appartements, à louer",Location appartement bien meublé et équipé à J...,"equipements : Ascenseur,Balcon,Climatisation,C...",https://www.avito.ma/fr/tamaris/appartements/A...
4,Maison 80m² Ain Diab,Casablanca,0.005571,0.142857,0.02,0.032944,0.142857,"Maisons et Villas, à louer","Location Maison à Ain Diab, proche Bd de la co...","equipements : Balcon,Cuisine Équipée",https://www.avito.ma/fr/a%C3%AFn_diab/maisons_...
...,...,...,...,...,...,...,...,...,...,...,...
593,Deux Appartements à louer à iraq bouargane AGADIR,Agadir,0.003816,0.000000,0.01,0.024973,0.142857,"Appartements, à louer",Réf : APL547/24\nDeux Appartements à louer lon...,equipements :,https://www.avito.ma/fr/autre_secteur/appartem...
594,Studio meublé à louer 40m² à Casablanca,Casablanca,0.006448,0.142857,0.02,0.035069,1.000000,"Appartements, à louer",jolie studio meublé en Location à Casablanca M...,"equipements : Ascenseur,Balcon,Chauffage,Clima...",https://www.avito.ma/fr/maarif/appartements/St...
595,شقة فارغة للكراء الشهري إقامة نجاح جيت سكن حي ...,Agadir,0.002500,0.142857,0.02,0.032944,0.142857,"Appartements, à louer",appartement a louer vide sur Quartier hay sala...,equipements :,https://www.avito.ma/fr/hay_salam/appartements...
596,Appartement à louer 102 m² à Casablanca,Casablanca,0.001448,0.000000,0.01,0.011690,0.285714,"Appartements, à louer",Magnifique appartement meublé dans une résiden...,"equipements : Ascenseur,Chauffage,Climatisatio...",https://www.avito.ma/fr/bourgogne/appartements...
597,APPARTEMENT NEUF A LOUER A RIAD GARDEN,Marrakech,0.002062,0.142857,0.01,0.022317,0.142857,"Appartements, à louer",NB immo vous proposer un appartement longue du...,"equipements : Ascenseur,Chauffage,Climatisatio...",https://www.avito.ma/fr/agdal/appartements/APP...

In [892]:
correlation_matrix = clean_normalized_df[['prix','N_chambre','N_salles_bain','surface', 'etage']].corr()
correlation_matrix

                   prix  N_chambre  N_salles_bain   surface     etage
prix           1.000000   0.058786       0.002596  0.061532 -0.024925
N_chambre      0.058786   1.000000       0.106285  0.538925  0.078426
N_salles_bain  0.002596   0.106285       1.000000  0.032351 -0.028450
surface        0.061532   0.538925       0.032351  1.000000  0.031056
etage         -0.024925   0.078426      -0.028450  0.031056  1.000000

In [894]:
df['localisation'].unique()

array(['Casablanca', 'Tamaris', 'Rabat', 'Oujda', 'Benslimane', 'Temara',
       'Tanger', nan, 'Marrakech', 'الدار البيضاء', 'Kénitra', 'Tétouan',
       'Had Soualem', 'Berrechid', 'El Jadida', 'Meknès', 'الرباط',
       'Mohammedia', 'Fès', 'Sidi Bouzid', 'Agadir', 'Ain Attig',
       'القنيطرة', 'Safi', 'Martil', 'El Mansouria', 'Nador',
       'Chefchaouen', 'Bouznika', 'Dakhla', 'Ben Guerir', 'Al Hoceima',
       'Salé', 'Bouskoura', 'Merzouga', 'Asilah', 'Cabo Negro',
       'El Menzeh', 'تمارة', 'Mdiq', 'Dar Bouazza'], dtype=object)

In [895]:
df['localisation'].value_counts()

localisation
Casablanca       250
Rabat             69
Tanger            47
Temara            35
Marrakech         32
Mohammedia        24
El Jadida         22
Agadir            22
Kénitra           19
Fès               11
Bouskoura         10
El Mansouria       8
Salé               5
Meknès             4
Berrechid          4
Safi               3
Bouznika           3
Sidi Bouzid        2
Tétouan            2
Martil             2
Nador              2
Al Hoceima         2
Ben Guerir         1
Asilah             1
Cabo Negro         1
Merzouga           1
El Menzeh          1
تمارة              1
Mdiq               1
Ain Attig          1
Dakhla             1
Chefchaouen        1
القنيطرة           1
Tamaris            1
الرباط             1
Had Soualem        1
الدار البيضاء      1
Benslimane         1
Oujda              1
Dar Bouazza        1
Name: count, dtype: int64

In [896]:
X = clean_normalized_df.drop('localisation', axis=1)
y = clean_normalized_df['localisation'].astype(str)

#One-hot encode categorical columns in X
X = pd.get_dummies(X, drop_first=True)

#Convert all boolean columns to integers (True -> 1, False -> 0)
X = X.apply(lambda col: col.astype(int) if col.dtype == 'bool' else col)

#Convert any non-numeric columns to numeric
X = X.apply(pd.to_numeric, errors='coerce')
X.fillna(X.mean(), inplace=True)

# Filter out classes with only one sample in the target column to avoid SMOTE errors
class_counts = y.value_counts()
classes_to_keep = class_counts[class_counts > 1].index  # Classes with more than one sample
X_filtered = X[y.isin(classes_to_keep)]
y_filtered = y[y.isin(classes_to_keep)]

#Apply SMOTE on the filtered data to balance classes in the target column 'localisation'
smote = SMOTE(random_state=42, k_neighbors=1)
X_res, y_res = smote.fit_resample(X_filtered, y_filtered)

In [897]:
class_counts = y_res.value_counts()
class_counts

localisation
Casablanca      222
Fès             222
Salé            222
Al Hoceima      222
Bouznika        222
Nador           222
El Mansouria    222
Martil          222
Safi            222
Agadir          222
Sidi Bouzid     222
Mohammedia      222
Rabat           222
Meknès          222
El Jadida       222
Berrechid       222
Tétouan         222
Kénitra         222
Marrakech       222
nan             222
Tanger          222
Temara          222
Bouskoura       222
Name: count, dtype: int64

In [898]:
# Convert the  X_res to a DataFrame
X_res_df = pd.DataFrame(X_res, columns=X.columns)
X_res_df

,prix,N_chambre,N_salles_bain,surface,etage,titre_2 Appartements à louer à berrechid,titre_2MARS - STUDIO NEUF A LOUER,titre_A californie appartement a louer vide,titre_A coté école albalssamé,titre_A louer Appartement prés clinique Badr(Bourgogne),...,lien_annonce_https://www.avito.ma/vi/55627321.htm,lien_annonce_https://www.avito.ma/vi/55659362.htm,lien_annonce_https://www.avito.ma/vi/55701347.htm,lien_annonce_https://www.avito.ma/vi/55711021.htm,lien_annonce_https://www.avito.ma/vi/55712894.htm,lien_annonce_https://www.avito.ma/vi/55720384.htm,lien_annonce_https://www.avito.ma/vi/55721621.htm,lien_annonce_https://www.avito.ma/vi/55721988.htm,lien_annonce_https://www.avito.ma/vi/55736293.htm,lien_annonce_https://www.avito.ma/vi/55736307.htm
0,0.007326,0.000000,0.010000,0.035069,0.000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.004255,0.000000,0.010000,0.035069,0.142857,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.006010,0.285714,0.020000,0.062168,0.285714,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.005571,0.142857,0.020000,0.032944,0.142857,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0.003378,0.142857,0.010000,0.027630,0.000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5101,0.009664,0.248271,0.027379,0.057026,0.459099,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5102,0.007869,0.206521,0.024456,0.048330,0.333848,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5103,0.008889,0.230246,0.026117,0.053271,0.405023,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5104,0.008697,0.225771,0.025804,0.052339,0.391600,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5105,0.006654,0.178247,0.022477,0.042440,0.249028,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [900]:
#Add the y_res as a new column 
X_res_df['localisation'] = y_res

C:\Users\Youcode\AppData\Local\Temp\ipykernel_964\55194684.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X_res_df['localisation'] = y_res

In [903]:
#cleaning the x-res
X_res_df=X_res_df[X_res_df['localisation']!='nan']
X_res_df

,prix,N_chambre,N_salles_bain,surface,etage,titre_2 Appartements à louer à berrechid,titre_2MARS - STUDIO NEUF A LOUER,titre_A californie appartement a louer vide,titre_A coté école albalssamé,titre_A louer Appartement prés clinique Badr(Bourgogne),...,lien_annonce_https://www.avito.ma/vi/55659362.htm,lien_annonce_https://www.avito.ma/vi/55701347.htm,lien_annonce_https://www.avito.ma/vi/55711021.htm,lien_annonce_https://www.avito.ma/vi/55712894.htm,lien_annonce_https://www.avito.ma/vi/55720384.htm,lien_annonce_https://www.avito.ma/vi/55721621.htm,lien_annonce_https://www.avito.ma/vi/55721988.htm,lien_annonce_https://www.avito.ma/vi/55736293.htm,lien_annonce_https://www.avito.ma/vi/55736307.htm,localisation
0,0.007326,0.000000,0.01,0.035069,0.000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Casablanca
1,0.004255,0.000000,0.01,0.035069,0.142857,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Casablanca
2,0.006010,0.285714,0.02,0.062168,0.285714,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Casablanca
3,0.005571,0.142857,0.02,0.032944,0.142857,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Casablanca
4,0.003378,0.142857,0.01,0.027630,0.000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Rabat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4881,0.002709,0.248271,0.01,0.037582,0.285714,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tétouan
4882,0.002453,0.206521,0.01,0.030905,0.285714,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tétouan
4883,0.002598,0.230246,0.01,0.034699,0.285714,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tétouan
4884,0.002571,0.225771,0.01,0.033984,0.285714,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tétouan
4885,0.002279,0.178247,0.01,0.026383,0.285714,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Tétouan

In [915]:
corr_X_res_df = X_res_df[['prix','N_chambre','N_salles_bain','surface', 'etage']].corr()
corr_X_res_df

                   prix  N_chambre  N_salles_bain   surface     etage
prix           1.000000   0.204842       0.021267  0.284250  0.000684
N_chambre      0.204842   1.000000       0.088698  0.619363  0.171824
N_salles_bain  0.021267   0.088698       1.000000  0.060296 -0.025689
surface        0.284250   0.619363       0.060296  1.000000  0.056547
etage          0.000684   0.171824      -0.025689  0.056547  1.000000